import Head from 'next/head'
import { Navbar, Footer } from '../components/global/index';
import { Main } from '../components/about/index';

export default function About() {
  return (
    <div className="bg-slate-50 min-h-screen min-w-screen">
      <Head>
        <title>John Pioc | Web3 Developer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar selected="About Me"/>
      <Main />
      <Footer />
    </div>
  )
}